################################################################################
#                                                                              #
# db    db  .8888.  dP     888888b 8888ba   .8888.     d8b   db 888888b d8888P #
# 88    88 d8'  `8b 88     88      88  `8b d8'  `8b    88V8  88 88        88   #
# Y8    8P 88    88 88    a88aaa   88aa8P' 88    88    88 V8 88 88aaa     88   #
# `8b  d8' 88    88 88     88      88  `8b 88    88    88  V888 88        88   #
#  `8bd8'  Y8.  .8P 88     88      88  .88 Y8.  .8P dP 88   V88 88        88   #
#    YP     `888P'  88888P 888888P 888888'  `888P'  88 VP    8P 888888P   dP   #
#                                                                              #
################################################################################

image: node:22

stages:
  - test
  - release


# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  key:
    files:
      - package.json
    prefix: node_modules
  paths:
    - node_modules/

# ------------------------------------------------------------------------------

before_script:
  - node --version
  - npm --version
  - npm install --quiet


test.lint:
  stage: test
  script:
    - npm install eslint-formatter-gitlab
    - npm run lint -- --format gitlab
  artifacts:
    reports:
      codequality: gl-codequality.json

test.test.20:
  stage: test
  image: node:20
  script:
    - npm run test

test.coverage:
  stage: test
  script:
    - npm run coverage

  coverage: '/Statements\s*:\s*([\d.%]+).*$/'

release:
  stage: release
  rules:
    # only for tags `v1.1.xxxxxxx(whatever)`
    - if: '$CI_COMMIT_TAG =~ /^release\//'
      when: manual

  script:
    - echo "//registry.npmjs.org/:_authToken=${VLB_CI_NPM_TOKEN}" > ~/.npmrc
    - npm whoami
    - npm publish
