# db    db  .8888.  dP     888888b 8888ba   .8888.     d8b   db  888888b d8888P
# 88    88 d8'  `8b 88     88      88  `8b d8'  `8b    88V8  88  88        88
# Y8    8P 88    88 88     88aaa   88aa8P' 88    88    88 V8 88 a88aaa     88
# `8b  d8' 88    88 88     88      88  `8b 88    88    88  V888  88        88
#  `8bd8'  Y8.  .8P 88     88      88  .88 Y8.  .8P dP 88   V88  88        88
#    YP     `888P'  88888P 888888P 888888'  `888P'  88 VP    8P  888888P   dP

# ESLint rules for volebo.net
#
# Copyright (C) 2016-2017 Volebo <dev@volebo.net>
# Copyright (C) 2016-2017 Maksim Koryukov <maxkoryukov@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

sudo: false

language: node_js

node_js:
  - 4
  - 6

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false

install:
  - npm install -g npm
  - npm install -g eslint
  - npm install
  # - npm install -g codecov
  # - npm install -g bithound

script:
  # - gulp build
  # - npm run lint
  - npm test

deploy:
  provider: npm
  api_key:
    secure: "J/Kq1wrIT4Wx5aqNJjztWnC98t79lU5aTPqCvkd5HlRljsRXM3B4hAFy0X64KYVKYpqMdLFMbjQeqCusa77HBDJaFqxTdqMJmsjBy/cUGrp4CeGXzXZcWQRXbRyEYj3OX1sPmeOfx73nj/0Suyqhro6DzKpI23uOl9hGrOch7zNV0VtrfQsmZt4Vp0nugvFJBReWaqGBHgyeelRAa+RDdsGvrMx3F/9uP5VP3x2oX+vmQvC4PRDxUHlyIqzo8igKp9fmRYh1HVH6wIetyxMuFibNKVsE+h8bfozNMUPt+H33UXxvKC+HKM8q96exw9/3a8knOgwu8hMCDWhNquxqKvY1rrK/YvEcPmPN8mcpj52z+sUUbK4ROVE+3AL0RIH+suFmMiqAs3+MDA91wXsM84ai8tOw4D9KPplrmR55pMbCNMy8ekkxCaP6lS6dEnN534ai12iOGbQY0U87F4+dTEq72Bf7oQDJuNJl7P14mbdmznp7G+FQ9io0nV5x8eAKxBL0KVsNN+Iqh4jKf752Dp7MdMpzwksN+oQ8OpsD28bGk9Ju7JVJmKHJ1z6d5d/OvGSj6rRsRiEvykN7vjH12qhS+zwKMjrtZmaAMHOWPB4vUETlcCskoWkQ0lbMQD4vv4KUuxEwYSmwhZ71znaJkYDATJNF7vRwJdo72hMI8q4="
  email: dev@volebo.net
  on:
    tags: true
    node_js: 6
    repo: volebo/eslint-config-volebo

after_deploy:
  # Send notification to Slack:
  - curl -sL https://raw.githubusercontent.com/volebo/dev/master/scripts/im/slack-publish.sh | bash -s -
